### ISSUE TITLE
مشکل امنیتی

### ISSUE THREAD

**Issue by ILYAGVC** [MrAminiNezhad/Raccoon#19]
جستجو با ایمیل بسیار نا ایمن است و ممکنه تحت حمله brute-force قرار بگیرد و به دلیل اینکه ایمیل ها اکثرا الگوی مشابهی دارند و کوتاه هستند به راحتی کرک می‌شوند، باید در این مورد فکری شود

**Comment by MrAminiNezhad** [comment]
سلام عزیز ، این مورد تو نسخه جدید حل میشه و از uuid استفاده میشه

**Comment by uzer98** [comment]
حالا کرک هم بشه
یه چه درد کسی میخوره
توی مشخصاتی که نمایش میده کانفیگ نمایش نمیده که بشه سو استفاده کرد

**Comment by MrAminiNezhad** [comment]
> حالا کرک هم بشه یه چه درد کسی میخوره توی مشخصاتی که نمایش میده کانفیگ نمایش نمیده که بشه سو استفاده کرد

دقیقا کاربرد خاصی نداره فقط طرف میتونه میزان حجم رو ببینه که مثلا یوزر 1 چقدر حجم داره ...

**Comment by ILYAGVC** [comment]
> حالا کرک هم بشه یه چه درد کسی میخوره توی مشخصاتی که نمایش میده کانفیگ نمایش نمیده که بشه سو استفاده کرد

اگه با uuid کرک بشه میشه بعنوان کانفیگ استفاده کرد

**Comment by MrAminiNezhad** [comment]
> > حالا کرک هم بشه یه چه درد کسی میخوره توی مشخصاتی که نمایش میده کانفیگ نمایش نمیده که بشه سو استفاده کرد
> 
> اگه با uuid کرک بشه میشه بعنوان کانفیگ استفاده کرد

اینو دیگه خود پنل های xui باید براش فکری بکنن، چون بدون اینم میشه با 4 خط کد پایتون این کارو کرد
