### ISSUE TITLE
اتصال چندین سرور مختلف

### ISSUE THREAD

**Issue by sepahna** [MrAminiNezhad/Raccoon#20]
ایا میشه چند سرور مختلف رو بهش وصل کرد؟

**Comment by mehdiyahyavi** [comment]
جناب امینی نژاد کار بسیار ارزشمندی کردن. برام جالبه که دو نفر با اختلاف 10 روزه، به بررسی یه مشکل پرداختن :-)
من api های این نسخه رو نتونستم کامل ببینم. اما بله، امکان اتصال چند سرور وجود داره. حتی سرویس ibsng
میتونیم در ارتباط باشیم

**Comment by MrAminiNezhad** [comment]
> ایا میشه چند سرور مختلف رو بهش وصل کرد؟

در این نسخه به یک سرور محدود شده ولیدر نسخه بعدی به راحتی میتونید چند پنل اضافه بکنید
> جناب امینی نژاد کار بسیار ارزشمندی کردن. برام جالبه که دو نفر با اختلاف 10 روزه، به بررسی یه مشکل پرداختن :-) من api های این نسخه رو نتونستم کامل ببینم. اما بله، امکان اتصال چند سرور وجود داره. حتی سرویس ibsng میتونیم در ارتباط باشیم

سلام دوست عزیز تشکر برای api ها میتونید به پروژه ثنایی یا علیرضا مراجعه بکنید تمام موارد اونجا هستش
