### ISSUE TITLE
خطا در تحلیل پاسخ JSON

### ISSUE THREAD

**Issue by sepahna** [MrAminiNezhad/Raccoon#21]
درود 
بعد از وارد کردن یوزر کاربر این خطا میاد

**Comment by MrAminiNezhad** [comment]
بررسی میشود

**Comment by MrAminiNezhad** [comment]
بررسی شد مشکلی نبود ممکنه یکی از مراحل را اشتباه انجام داده باشید

**Comment by thezass** [comment]
برای من هم این مشکل درست شد توی هاست و دلیلش این هست که هیچ کوکی ذخیره نمیشه برای رکوعست api اما نفهمیدم دلیلش چیه که هیچ کوکی برنمیگردونه وقتی رکوعست میزنه به سرور vpn
