### ISSUE TITLE
خطا در اجرای مرحله ورود به پنل

### ISSUE THREAD

**Issue by alrz-usfi** [MrAminiNezhad/Raccoon#22]
روی هاست ایران تست کردم این ارور نشون داده میشه:

خطا در اجرای مرحله ورود به پنل: Peer reports incompatible or unsupported protocol version.

ssl هم فعال نیست

**Comment by MrAminiNezhad** [comment]
سلام معمولا 2 علت داره 
1- عدم قرار دادن / در اخر ادرس پنل
2- مسدود بودن پورت پنل روی هاست پیشنهاد میشود پورت هایی مانند 2087، 2096 ، 443 و... استفاده بکنید
