### ISSUE TITLE
خطا برای کانفیگهای بدون حجم 

### ISSUE THREAD

**Issue by Nima786** [MrAminiNezhad/Raccoon#25]
وقتی کانفیگی که محدودیت حجم نداره رو تست میکنم خطای 500 میده

**Comment by MrAminiNezhad** [comment]
خطای 500 مربوط به هاست شماست اینو به هاستینگ گذارش باید بدین

**Comment by Nima786** [comment]
از هاستینگ نگرفتم خودم کنترل پنل نصب کردم روی سرور مجازیم. اکستنشن خاصی از php باید نصب باشه؟
در ضمن فکر میکنم فونتها درست کار نمیکنن.

**Comment by Nima786** [comment]
من توی inspect چک کردم دیدم فایل فونت رو میخواد از داخل پوشه css بخونه، در حالیکه باید در پوشه فونت بخونه، برا تست فونت رو داخل پوشه css هم کپی کردم و درست شد.

**Comment by MrAminiNezhad** [comment]
چک میشه گذارشتون

**Comment by MrAminiNezhad** [comment]
بررسی شد سورس اپدیت و متد ادرس فونت تغییر کرد

**Comment by Nima786** [comment]
من تست کردم باید همه url ها به اون صورت دربیان وگرنه بازم کار نمیکنه، شما فقط یکی اولی رو درست کردین.
در مورد خطایی که برای کانفیگهای نامحدود میده نظری ندارین؟ چون برای بقیه سرچ ها که نامحدود نیستن مشکلی نداره و کار میکنه؟

**Comment by MrAminiNezhad** [comment]
تست شده خطایی در سرویس ههی نامحدود نیستش

**Comment by Nima786** [comment]
مشکل رو پیدا کردم، اسکریپت شما با php 8.x به بالا سازگار نیست برای همین به نامحدود که میرسه خطای 500 میده ، ورژن رو آوردم روی 7.4 و درست شد.
