### ISSUE TITLE
اطلاعاتی با این یوزرنیم پیدا نشد

### ISSUE THREAD

**Issue by uzer0098** [MrAminiNezhad/Raccoon#41]
تو نسخه 1.3.0 اطلاعات نمیاره

```

اطلاعاتی با این یوزرنیم پیدا نشد
cannot find any information with this username

```

**Comment by thezass** [comment]
سلام اطلاعات پنل و درست وارد نکردید که بتونه اطلاعات و بگیره

**Comment by uzer0098** [comment]
اطلاعات ورود چندبار تست کردم
باز همون مشکل وجود داره

**Comment by thezass** [comment]
پورت پنل و تایپ هم دقت کنید alireza , sanaei 
پورت نباید توی هاست بلاک باشه
