### ISSUE TITLE
تشخیص ندادن اینباد ها

### ISSUE THREAD

**Issue by Ho3einCyber** [MrAminiNezhad/Raccoon#46]
سلام، یه مشکلی که وجود داره اینه که اسکریپت فقط کلاینت ها رو شناسایی میکنه و مشخصاتشو میده و خود اینباند هارو شناسایی نمیکنه!

مثلا من یک اینباد ساختم به اسم Test و قسمت اسم کلاینت هم خالی گذاشتم، و وقتی کانفیگ رو وارد اسکریپت میکنم نمیتونه تشخیص بده و میگه که اطلاعاتی با این یوزرنیم یافت نشد.

**Comment by MrAminiNezhad** [comment]
اسکریپت فقط کلاینت هارو چک میکنه و اینباند چک نمیکنه
