### ISSUE TITLE
درخواست امکانات 

### ISSUE THREAD

**Issue by uzer98** [MrAminiNezhad/Raccoon#49]
سلام
اگر بتونید این‌امکانات را اضافه کنید عالی میشه

۱- خرید اکانت
۲- تمدید اکانت

**Comment by MrAminiNezhad** [comment]
سلام دوست عزیز قالبت اضافه کردن امکانات فوق هست و درحال بررسی نهایی هستم ولی تایم دقیقی نمیتونم برای این امکانات اعلام بکنم
