### ISSUE TITLE
پیشنهاد 

### ISSUE THREAD

**Issue by Saeedroshan1906** [MrAminiNezhad/Raccoon#51]
سلام و عرض خسته نباشید به شما تیم عزیز 
یک پیشنهاد ، 
اگر امکانش هست لینک نرم افزار های مورد نیاز برای پلتفرم ها رو در صفحه اصلی قرار بدید 
که مثلا من لینک رو به کاربر بدم از اونجا نرم افزار مورد نیازش و دانلود کنه بعد اگه خواست بررسی کنه چون الان تا وارد نشه نمیتونه به دکمه های دانلود برسه ، باز هم تشکر از تیم خوبتون

**Comment by MrAminiNezhad** [comment]
حتمه بررسی میشه
