### ISSUE TITLE
عدم نمایش اطلاعات پنل دوم به بعد

### ISSUE THREAD

**Issue by aliamg1356** [MrAminiNezhad/Raccoon#53]
با سلام
در صورت اضافه کردن چند پنل(حتی دو پنل)پنل اول را میتواند نمایش دهد ولی از پنل دوم به بعد خطا میدهد و نمیتواند یوزر را پیدا کند

**Comment by MrAminiNezhad** [comment]
سلام دوست عزیز این مشکل از سمت اشتباه وارد کردن اطلاعات از سمت شما میباشد حتما از حالت کامنت کد هارا خارج بکنید

**Comment by aliamg1356** [comment]
> سلام دوست عزیز این مشکل از سمت اشتباه وارد کردن اطلاعات از سمت شما میباشد حتما از حالت کامنت کد هارا خارج بکنید
![Untitled](https://github.com/MrAminiNezhad/Raccoon/assets/124570423/ea0a22b8-8ae8-4d12-b0f2-7ee56a74ed58)
دقت کنید عین هم تنظیم شده اند
