### ISSUE TITLE
استفاده بدون هاست

### ISSUE THREAD

**Issue by l3lack-eyes** [MrAminiNezhad/Raccoon#7]
سلام 
خسته نباشید 
امکانش هست در آپدیت بعدی اضافه کردن به vps که کانفیگ هاروش هست هم انجام بدید

**Comment by MrAminiNezhad** [comment]
سلام دوست عزیز ، بررسی میشه این مورد ولی خب چون برای نمایش روی سرور نیاز هست که Nginx نصب بشه این سیستم پورت 443 و پورت 80 را در گیر میکنه  و باعث خطا در پنل X-UI میشه ... به هر حال بررسی میکنیم اگر شد انجام میشه حتما
